# Identificación del proyecto 
sonar.projectKey=jorgeg1824
sonar.organization=jorgeg1824
sonar.projectName=Sistema de Parqueaderos - Backend
sonar.projectVersion=1.0.0

# Fuentes
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Exclusiones 
# No analizar entidades JPA ni clases generadas automáticamente
sonar.exclusions=\
  **/entity/**,\
  **/sql/jpa/entity/**,\
  **/*Application.java

sonar.coverage.exclusions=\
  **/entity/**,\
  **/sql/jpa/entity/**,\
  **/*Application.java

# Encoding 
sonar.sourceEncoding=UTF-8